/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ABottle {
        /**
          * The list of colors represented as an array
         */
        "colors": string;
        /**
          * Indicate a winning state
         */
        "finished": boolean;
        /**
          * Indicate that the bottle is selected
         */
        "selected": boolean;
        /**
          * Indicate that the bottle cannot be targeted
         */
        "warning": boolean;
    }
    interface AColor {
        /**
          * The list of colors represented as an array
         */
        "color": string;
    }
}
declare global {
    interface HTMLABottleElement extends Components.ABottle, HTMLStencilElement {
    }
    var HTMLABottleElement: {
        prototype: HTMLABottleElement;
        new (): HTMLABottleElement;
    };
    interface HTMLAColorElement extends Components.AColor, HTMLStencilElement {
    }
    var HTMLAColorElement: {
        prototype: HTMLAColorElement;
        new (): HTMLAColorElement;
    };
    interface HTMLElementTagNameMap {
        "a-bottle": HTMLABottleElement;
        "a-color": HTMLAColorElement;
    }
}
declare namespace LocalJSX {
    interface ABottle {
        /**
          * The list of colors represented as an array
         */
        "colors"?: string;
        /**
          * Indicate a winning state
         */
        "finished"?: boolean;
        /**
          * Indicate that the bottle is selected
         */
        "selected"?: boolean;
        /**
          * Indicate that the bottle cannot be targeted
         */
        "warning"?: boolean;
    }
    interface AColor {
        /**
          * The list of colors represented as an array
         */
        "color"?: string;
    }
    interface IntrinsicElements {
        "a-bottle": ABottle;
        "a-color": AColor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "a-bottle": LocalJSX.ABottle & JSXBase.HTMLAttributes<HTMLABottleElement>;
            "a-color": LocalJSX.AColor & JSXBase.HTMLAttributes<HTMLAColorElement>;
        }
    }
}
